// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class SOAP12SupportedEnvType;

/**
 (public class)
 
*/
@interface SOAP12UpgradeType : NSObject <PicoBindable> {

@private
    NSMutableArray *_supportedEnvelope;

}


/**
 (public property)
 
 entry type : class SOAP12SupportedEnvType
*/

@property (nonatomic, retain) NSMutableArray *supportedEnvelope;


@end
