// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import "StockQuoteSoap_SOAPClient.h"

@implementation StockQuoteSoap_SOAPClient

-(void)getQuote:(GetQuote *) requestObject 
      success:(void (^)(GetQuoteResponse *responseObject))success
      failure:(void (^)(NSError *error, id<PicoBindable> soapFault))failure {
 
     [super setDefaultHeader:@"SOAPAction" value: @"http://www.webserviceX.NET/GetQuote"];
 
     [super invoke:requestObject responseClass:[GetQuoteResponse class]
     success:^(PicoSOAPRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoSOAPRequestOperation *operation, NSError *error, id<PicoBindable> soapFault) {
         if (failure) {
             failure(error, soapFault);
         }
     }];
}


@end