// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "SearchItem.h"
#import "GalleryInfoContainer.h"
#import "ShippingInfo.h"
#import "ListingInfo.h"
#import "Condition.h"
#import "Distance.h"
#import "Storefront.h"
#import "UnitPriceInfo.h"
#import "ProductId.h"
#import "ItemAttribute.h"
#import "Category.h"
#import "SellingStatus.h"
#import "DiscountPriceInfo.h"
#import "SellerInfo.h"

@implementation SearchItem

@synthesize itemId = _itemId;
@synthesize title = _title;
@synthesize globalId = _globalId;
@synthesize subtitle = _subtitle;
@synthesize primaryCategory = _primaryCategory;
@synthesize secondaryCategory = _secondaryCategory;
@synthesize galleryURL = _galleryURL;
@synthesize galleryInfoContainer = _galleryInfoContainer;
@synthesize viewItemURL = _viewItemURL;
@synthesize charityId = _charityId;
@synthesize productId = _productId;
@synthesize paymentMethod = _paymentMethod;
@synthesize autoPay = _autoPay;
@synthesize postalCode = _postalCode;
@synthesize location = _location;
@synthesize country = _country;
@synthesize storeInfo = _storeInfo;
@synthesize sellerInfo = _sellerInfo;
@synthesize shippingInfo = _shippingInfo;
@synthesize sellingStatus = _sellingStatus;
@synthesize listingInfo = _listingInfo;
@synthesize returnsAccepted = _returnsAccepted;
@synthesize galleryPlusPictureURL = _galleryPlusPictureURL;
@synthesize compatibility = _compatibility;
@synthesize distance = _distance;
@synthesize condition = _condition;
@synthesize isMultiVariationListing = _isMultiVariationListing;
@synthesize discountPriceInfo = _discountPriceInfo;
@synthesize pictureURLSuperSize = _pictureURLSuperSize;
@synthesize pictureURLLarge = _pictureURLLarge;
@synthesize unitPrice = _unitPrice;
@synthesize attribute = _attribute;
@synthesize topRatedListing = _topRatedListing;
@synthesize delimiter = _delimiter;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"itemId" propertyName:@"itemId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"title" propertyName:@"title" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"title"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"globalId" propertyName:@"globalId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"globalId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"subtitle" propertyName:@"subtitle" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"subtitle"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"primaryCategory" propertyName:@"primaryCategory" type:PICO_TYPE_OBJECT clazz:[Category class]];
    [map setObject:ps forKey:@"primaryCategory"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"secondaryCategory" propertyName:@"secondaryCategory" type:PICO_TYPE_OBJECT clazz:[Category class]];
    [map setObject:ps forKey:@"secondaryCategory"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"galleryURL" propertyName:@"galleryURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"galleryURL"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"galleryInfoContainer" propertyName:@"galleryInfoContainer" type:PICO_TYPE_OBJECT clazz:[GalleryInfoContainer class]];
    [map setObject:ps forKey:@"galleryInfoContainer"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"viewItemURL" propertyName:@"viewItemURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"viewItemURL"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"charityId" propertyName:@"charityId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"charityId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"productId" propertyName:@"productId" type:PICO_TYPE_OBJECT clazz:[ProductId class]];
    [map setObject:ps forKey:@"productId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"paymentMethod" propertyName:@"paymentMethod" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"paymentMethod"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"autoPay" propertyName:@"autoPay" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"autoPay"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"postalCode" propertyName:@"postalCode" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"postalCode"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"location" propertyName:@"location" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"location"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"country" propertyName:@"country" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"country"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"storeInfo" propertyName:@"storeInfo" type:PICO_TYPE_OBJECT clazz:[Storefront class]];
    [map setObject:ps forKey:@"storeInfo"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"sellerInfo" propertyName:@"sellerInfo" type:PICO_TYPE_OBJECT clazz:[SellerInfo class]];
    [map setObject:ps forKey:@"sellerInfo"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"shippingInfo" propertyName:@"shippingInfo" type:PICO_TYPE_OBJECT clazz:[ShippingInfo class]];
    [map setObject:ps forKey:@"shippingInfo"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"sellingStatus" propertyName:@"sellingStatus" type:PICO_TYPE_OBJECT clazz:[SellingStatus class]];
    [map setObject:ps forKey:@"sellingStatus"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"listingInfo" propertyName:@"listingInfo" type:PICO_TYPE_OBJECT clazz:[ListingInfo class]];
    [map setObject:ps forKey:@"listingInfo"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"returnsAccepted" propertyName:@"returnsAccepted" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"returnsAccepted"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"galleryPlusPictureURL" propertyName:@"galleryPlusPictureURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"galleryPlusPictureURL"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"compatibility" propertyName:@"compatibility" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"compatibility"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"distance" propertyName:@"distance" type:PICO_TYPE_OBJECT clazz:[Distance class]];
    [map setObject:ps forKey:@"distance"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"condition" propertyName:@"condition" type:PICO_TYPE_OBJECT clazz:[Condition class]];
    [map setObject:ps forKey:@"condition"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"isMultiVariationListing" propertyName:@"isMultiVariationListing" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"isMultiVariationListing"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"discountPriceInfo" propertyName:@"discountPriceInfo" type:PICO_TYPE_OBJECT clazz:[DiscountPriceInfo class]];
    [map setObject:ps forKey:@"discountPriceInfo"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"pictureURLSuperSize" propertyName:@"pictureURLSuperSize" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"pictureURLSuperSize"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"pictureURLLarge" propertyName:@"pictureURLLarge" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"pictureURLLarge"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"unitPrice" propertyName:@"unitPrice" type:PICO_TYPE_OBJECT clazz:[UnitPriceInfo class]];
    [map setObject:ps forKey:@"unitPrice"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"attribute" propertyName:@"attribute" type:PICO_TYPE_OBJECT clazz:[ItemAttribute class]];
    [map setObject:ps forKey:@"attribute"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"topRatedListing" propertyName:@"topRatedListing" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"topRatedListing"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"delimiter" propertyName:@"delimiter" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"delimiter"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.itemId = nil;
    self.title = nil;
    self.globalId = nil;
    self.subtitle = nil;
    self.primaryCategory = nil;
    self.secondaryCategory = nil;
    self.galleryURL = nil;
    self.galleryInfoContainer = nil;
    self.viewItemURL = nil;
    self.charityId = nil;
    self.productId = nil;
    self.paymentMethod = nil;
    self.autoPay = nil;
    self.postalCode = nil;
    self.location = nil;
    self.country = nil;
    self.storeInfo = nil;
    self.sellerInfo = nil;
    self.shippingInfo = nil;
    self.sellingStatus = nil;
    self.listingInfo = nil;
    self.returnsAccepted = nil;
    self.galleryPlusPictureURL = nil;
    self.compatibility = nil;
    self.distance = nil;
    self.condition = nil;
    self.isMultiVariationListing = nil;
    self.discountPriceInfo = nil;
    self.pictureURLSuperSize = nil;
    self.pictureURLLarge = nil;
    self.unitPrice = nil;
    self.attribute = nil;
    self.topRatedListing = nil;
    self.delimiter = nil;
    self.any = nil;
    [super dealloc];
}

@end
