// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class SearchItem;

/**
 
 Contains the returned item listings, if any. The data for each listing is
 returned in individual item containers.
 
 
 @ingroup FindingServicePortType
*/
@interface SearchResult : NSObject <PicoBindable> {

@private
    NSMutableArray *_item;
    NSString *_delimiter;
    NSMutableArray *_any;
    NSNumber *_count;

}


/**
 
 Container for the data of a single item that matches the search criteria.
 
 
 entry type : class SearchItem
*/

@property (nonatomic, retain) NSMutableArray *item;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *delimiter;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *count;


@end
