// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_StoreVacationPreferencesType.h"

@implementation Trading_StoreVacationPreferencesType

@synthesize onVacation = _onVacation;
@synthesize returnDate = _returnDate;
@synthesize hideFixedPriceStoreItems = _hideFixedPriceStoreItems;
@synthesize messageItem = _messageItem;
@synthesize messageStore = _messageStore;
@synthesize displayMessageStoreCustomText = _displayMessageStoreCustomText;
@synthesize messageStoreCustomText = _messageStoreCustomText;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OnVacation" propertyName:@"onVacation" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"onVacation"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ReturnDate" propertyName:@"returnDate" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"returnDate"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"HideFixedPriceStoreItems" propertyName:@"hideFixedPriceStoreItems" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"hideFixedPriceStoreItems"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageItem" propertyName:@"messageItem" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"messageItem"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageStore" propertyName:@"messageStore" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"messageStore"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DisplayMessageStoreCustomText" propertyName:@"displayMessageStoreCustomText" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"displayMessageStoreCustomText"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageStoreCustomText" propertyName:@"messageStoreCustomText" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"messageStoreCustomText"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.onVacation = nil;
    self.returnDate = nil;
    self.hideFixedPriceStoreItems = nil;
    self.messageItem = nil;
    self.messageStore = nil;
    self.displayMessageStoreCustomText = nil;
    self.messageStoreCustomText = nil;
    [super dealloc];
}

@end
