// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_MyMessagesForwardDetailsType.h"

@implementation Trading_MyMessagesForwardDetailsType

@synthesize userForwardDate = _userForwardDate;
@synthesize forwardMessageEncoding = _forwardMessageEncoding;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserForwardDate" propertyName:@"userForwardDate" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"userForwardDate"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ForwardMessageEncoding" propertyName:@"forwardMessageEncoding" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"forwardMessageEncoding"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.userForwardDate = nil;
    self.forwardMessageEncoding = nil;
    self.any = nil;
    [super dealloc];
}

@end
