// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_AmountType;

/**
 
 This type is deprecated as Cross Promotions are no longer supported in the APIs.
 
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_PromotionDetailsType : NSObject <PicoBindable> {

@private
    Trading_AmountType *_promotionPrice;
    NSString *_promotionPriceType;
    NSNumber *_bidCount;
    Trading_AmountType *_convertedPromotionPrice;
    NSMutableArray *_any;

}


/**
 
 
 The price of the cross-promoted item in the currency of the site upon which
 the item is listed. If the item is listed on a site different
 from the site specified in the request, then ConvertedPromotionPrice is also
 returned. Not related to the Promotional Price Display feature.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *promotionPrice;

/**
 
 
 The listing type for the promoted item and how the item price is used. Not
 related to the Promotional Price Display feature.
 
 
 type: string constant in Trading_PromotionItemPriceTypeCodeType.h
*/
@property (nonatomic, retain) NSString *promotionPriceType;

/**
 
 
 Bid count if the item is an auction item and has bids.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *bidCount;

/**
 
 
 The converted price of the cross-promoted item. Emitted
 only when the item is listed on a site other than the site specified in the
 request. Returns the price in the currency of the site specified in the
 request. Not related to the Promotional Price Display feature.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *convertedPromotionPrice;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
