// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractRequestType.h"


@class Trading_TaxTableType;

/**
 
 Sets the tax table for a seller on a given site.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_SetTaxTableRequestType : Trading_AbstractRequestType {

@private
    Trading_TaxTableType *_taxTable;

}


/**
 
 A container of tax jurisdiction information unique to a user/site combination.
 
 
 type : class Trading_TaxTableType
*/
@property (nonatomic, retain) Trading_TaxTableType *taxTable;


@end
