// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_MismatchTypeCodeType.h"

/**
 @file
 
 Enumeration type that indicates whether the buyer's payment was above or below the actual
 total cost of an order going through the new eBay payment process.
 
*/

/**
 
 This value indicates that the buyer paid more than the required amount.
 
*/
NSString *const Trading_MismatchTypeCodeType_OVER_PAYMENT = @"OverPayment";

/**
 
 This value indicates that the buyer paid less than the required amount.
 
*/
NSString *const Trading_MismatchTypeCodeType_UNDER_PAYMENT = @"UnderPayment";

/**
 
 (out) Reserved for internal or future use
 
*/
NSString *const Trading_MismatchTypeCodeType_CUSTOM_CODE = @"CustomCode";
