// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Combined Purchase Options
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Combined payments are not allowed by seller.
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_NO_COMBINED_PAYMENT;

/**
 
 Yes. Specify discount now.
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_DISCOUNT_SPECIFIED;

/**
 
 Yes. Specify discount later.
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_SPECIFY_DISCOUNT_LATER;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_CUSTOM_CODE;
