// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 Container for top-rated seller program information.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_TopRatedSellerDetailsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_topRatedProgram;
    NSMutableArray *_any;

}


/**
 
 Top-rated seller program details for the seller. Returned when the seller is qualified as a top-rated seller.
 
 
 entry type : string constant in Trading_TopRatedProgramCodeType.h
*/

@property (nonatomic, retain) NSMutableArray *topRatedProgram;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
