// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_VeROReportPacketStatusCodeType.h"

/**
 @file
 
 The status of a set of items (packet) reported for infringement. Packet states 
 are based on the states of the reported items within the packet.
 
*/

/**
 
 (out) The packet has been received by eBay.
 
*/
NSString *const Trading_VeROReportPacketStatusCodeType_RECEIVED = @"Received";

/**
 
 (out) The packet is being processed by eBay.
 
*/
NSString *const Trading_VeROReportPacketStatusCodeType_IN_PROCESS = @"InProcess";

/**
 
 (out) The packet has been processed by eBay. Each item within the packet has a status of Removed, SubmissionFailed, or ClarificationRequired.
 
*/
NSString *const Trading_VeROReportPacketStatusCodeType_PROCESSED = @"Processed";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_VeROReportPacketStatusCodeType_CUSTOM_CODE = @"CustomCode";
