// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


/**
 
 The question has been answered at least once.
 
*/
extern NSString *const Trading_MessageStatusTypeCodeType_ANSWERED;

/**
 
 The question has not yet been answered.
 
*/
extern NSString *const Trading_MessageStatusTypeCodeType_UNANSWERED;

/**
 
 Reserved for future or internal use.
 
*/
extern NSString *const Trading_MessageStatusTypeCodeType_CUSTOM_CODE;
