// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_MyMessagesResponseDetailsType;
@class Trading_MyMessagesFolderType;
@class Trading_MyMessagesForwardDetailsType;

/**
 
 This type is deprecated because <b>MyMessagesAlert*</b> are deprecated.
 
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_MyMessagesAlertType : NSObject <PicoBindable> {

@private
    NSString *_sender;
    NSString *_recipientUserID;
    NSString *_subject;
    NSString *_priority;
    NSString *_alertID;
    NSString *_externalAlertID;
    NSString *_contentType;
    NSString *_text;
    NSString *_resolutionStatus;
    NSNumber *_read;
    NSDate *_creationDate;
    NSDate *_receiveDate;
    NSDate *_expirationDate;
    NSDate *_resolutionDate;
    NSDate *_lastReadDate;
    NSString *_itemID;
    NSNumber *_isTimedResolution;
    NSString *_actionURL;
    Trading_MyMessagesResponseDetailsType *_responseDetails;
    Trading_MyMessagesForwardDetailsType *_forwardDetails;
    Trading_MyMessagesFolderType *_folder;
    NSMutableArray *_any;

}


/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the display name of the eBay application that
 sends the alert.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sender;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the displayable user ID of the recipient.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *recipientUserID;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the subject of the alert.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *subject;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained a number ranging from 0 to 10000 (inclusive),
 with 10000 having the highest priority.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *priority;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained an ID that uniquely identifies an alert for a
 given user.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *alertID;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained an ID used by an external application to
 uniquely identify an alert.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *externalAlertID;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the content type of the body text. The two
 acceptable values are "TEXT" and "HTML" (case
 sensitive).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *contentType;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the alert body. This can be either plain text
 or HTML, depending on which format the alert was
 originally written in. Note that the API does not
 currently check the user email format preferences
 that can be specified in My Messages on the eBay.com
 Web site.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *text;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained whether or not an alert was resolved, and how.
 
 
 type: string constant in Trading_MyMessagesAlertResolutionStatusCode.h
*/
@property (nonatomic, retain) NSString *resolutionStatus;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained whether or not an alert was viewed by a given
 user. Note that retrieving an alert with the API
 does not mark it as read.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *read;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the date and time an alert was created by a sender.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *creationDate;

/**
 
 The date and time that an alert was received
 by My Messages and stored in a database for the
 recipient.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *receiveDate;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the date and time at which an alert expires.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *expirationDate;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the date and time at which an alert is resolved.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *resolutionDate;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained the date and time an alert was last viewed by
 a given user.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *lastReadDate;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained a unique eBay item ID associated with an
 alert.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained whether or not a time-delayed
 resolution is applicable for an alert.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isTimedResolution;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained a URL that the recipient must visit to resolve
 an alert. May be returned as an empty tag if there is no applicable URL.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *actionURL;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained details relating to the response to an alert
 or message.
 
 
 type : class Trading_MyMessagesResponseDetailsType
*/
@property (nonatomic, retain) Trading_MyMessagesResponseDetailsType *responseDetails;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained details relating to the forwarding of an alert
 or message. Only returned if the alert or message is
 forwarded.
 
 
 type : class Trading_MyMessagesForwardDetailsType
*/
@property (nonatomic, retain) Trading_MyMessagesForwardDetailsType *forwardDetails;

/**
 
 
 This field will be deprecated in an upcoming release.
 This field formerly
 contained details relating to a My Messages folder.
 
 
 type : class Trading_MyMessagesFolderType
*/
@property (nonatomic, retain) Trading_MyMessagesFolderType *folder;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
