// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractResponseType.h"



/**
 
 Confirms the identity of the user by returning the UserID and the EIASToken belonging to
 the user.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_ConfirmIdentityResponseType : Trading_AbstractResponseType {

@private
    NSString *_userID;

}


/**
 
 Unique eBay user ID for the user.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *userID;


@end
