// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_GetUserContactDetailsResponseType.h"
#import "Trading_AddressType.h"

@implementation Trading_GetUserContactDetailsResponseType

@synthesize userID = _userID;
@synthesize contactAddress = _contactAddress;
@synthesize registrationDate = _registrationDate;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetUserContactDetailsResponse" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserID" propertyName:@"userID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"userID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ContactAddress" propertyName:@"contactAddress" type:PICO_TYPE_OBJECT clazz:[Trading_AddressType class]];
    [map setObject:ps forKey:@"contactAddress"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RegistrationDate" propertyName:@"registrationDate" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"registrationDate"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.userID = nil;
    self.contactAddress = nil;
    self.registrationDate = nil;
    [super dealloc];
}

@end
