// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 Indicates the sites on which a seller is eligible to offer IMCC as a payment method.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_IntegratedMerchantCreditCardInfoType : NSObject <PicoBindable> {

@private
    NSMutableArray *_supportedSite;
    NSMutableArray *_any;

}


/**
 
 Indicates a site on which a seller has a payment gateway account (and thus
 a site on which the seller can use the IntegratedMerchantCreditCard payment method).
 
 
 entry type : string constant in Trading_SiteCodeType.h
*/

@property (nonatomic, retain) NSMutableArray *supportedSite;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
