// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Used to indicate whether Default, WorkFlow A or WorkFlow B is applicable for a category.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Default Escrow timelines apply.
 
*/
extern NSString *const Trading_INEscrowWorkflowTimelineCodeType_DEFAULT;

/**
 
 Special Escrow timelines for Workflow A applies.
 
*/
extern NSString *const Trading_INEscrowWorkflowTimelineCodeType_WORKFLOW_A;

/**
 
 Special Escrow timelines for Workflow B applies.
 
*/
extern NSString *const Trading_INEscrowWorkflowTimelineCodeType_WORKFLOW_B;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_INEscrowWorkflowTimelineCodeType_CUSTOM_CODE;
