// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 Retrieves data for a specific, active Want It Now post identified by a post ID.
 The response includes the following fields: CategoryID, Description, PostID,
 Site, StartTime, ResponseCount, and Title. Although GetWantItNowSearchResults
 returns most of this information, only GetWantItNowPost returns Description for
 a post.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_GetWantItNowPostRequestType : Trading_AbstractRequestType {

@private
    NSString *_postID;

}


/**
 
 Specifies the post ID that uniquely identifies the Want It Now post for
 which to retrieve the data. PostID is a required input. PostID is unique
 across all eBay sites.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *postID;


@end
