// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_StoreColorSchemeArrayType;
@class Trading_StoreThemeType;

/**
 
 Set of Store themes.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_StoreThemeArrayType : NSObject <PicoBindable> {

@private
    NSMutableArray *_theme;
    Trading_StoreColorSchemeArrayType *_genericColorSchemeArray;
    NSMutableArray *_any;

}


/**
 
 A Store theme.
 
 
 entry type : class Trading_StoreThemeType
*/

@property (nonatomic, retain) NSMutableArray *theme;

/**
 
 Set of color schemes. This set is for use with those themes that do
 not explicitly list a color scheme in the theme definition (these
 themes are also known as advanced themes).
 
 
 type : class Trading_StoreColorSchemeArrayType
*/
@property (nonatomic, retain) Trading_StoreColorSchemeArrayType *genericColorSchemeArray;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
