// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


/**
 
 The full Store header is used.
 
*/
extern NSString *const Trading_StoreHeaderStyleCodeType_FULL;

/**
 
 A minimized Store header is used.
 
*/
extern NSString *const Trading_StoreHeaderStyleCodeType_MINIMIZED;

/**
 
    (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreHeaderStyleCodeType_CUSTOM_CODE;
