// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_OfferType;

/**
 
 Container for a list of offers. May contain zero, one, or multiple
 OfferType objects, each of which represents one offer extended by
 a user on a listing.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_CancelOfferType : NSObject <PicoBindable> {

@private
    Trading_OfferType *_offer;
    NSString *_explanation;
    NSMutableArray *_any;

}


/**
 
 Contains the data for one offer. This includes: data for the user making the
 offer, the amount of the offer, the quantity of items being bought from the
 listing, the type of offer being made, and more.
 
 
 type : class Trading_OfferType
*/
@property (nonatomic, retain) Trading_OfferType *offer;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *explanation;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
