// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_AnnouncementMessageType.h"

@implementation Trading_AnnouncementMessageType

@synthesize announcementStartTime = _announcementStartTime;
@synthesize eventTime = _eventTime;
@synthesize messageType = _messageType;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AnnouncementStartTime" propertyName:@"announcementStartTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"announcementStartTime"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EventTime" propertyName:@"eventTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"eventTime"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageType" propertyName:@"messageType" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"messageType"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.announcementStartTime = nil;
    self.eventTime = nil;
    self.messageType = nil;
    self.any = nil;
    [super dealloc];
}

@end
