// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_CombinedPaymentOptionCodeType.h"

/**
 @file
 
 Combined Purchase Options
 
*/

/**
 
 Combined payments are not allowed by seller.
 
*/
NSString *const Trading_CombinedPaymentOptionCodeType_NO_COMBINED_PAYMENT = @"NoCombinedPayment";

/**
 
 Yes. Specify discount now.
 
*/
NSString *const Trading_CombinedPaymentOptionCodeType_DISCOUNT_SPECIFIED = @"DiscountSpecified";

/**
 
 Yes. Specify discount later.
 
*/
NSString *const Trading_CombinedPaymentOptionCodeType_SPECIFY_DISCOUNT_LATER = @"SpecifyDiscountLater";

/**
 
 Reserved for internal or future use.
 
*/
NSString *const Trading_CombinedPaymentOptionCodeType_CUSTOM_CODE = @"CustomCode";
