// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_SellerRoleMetricsType.h"

@implementation Trading_SellerRoleMetricsType

@synthesize positiveFeedbackLeftCount = _positiveFeedbackLeftCount;
@synthesize negativeFeedbackLeftCount = _negativeFeedbackLeftCount;
@synthesize neutralFeedbackLeftCount = _neutralFeedbackLeftCount;
@synthesize feedbackLeftPercent = _feedbackLeftPercent;
@synthesize repeatBuyerCount = _repeatBuyerCount;
@synthesize repeatBuyerPercent = _repeatBuyerPercent;
@synthesize uniqueBuyerCount = _uniqueBuyerCount;
@synthesize transactionPercent = _transactionPercent;
@synthesize crossBorderTransactionCount = _crossBorderTransactionCount;
@synthesize crossBorderTransactionPercent = _crossBorderTransactionPercent;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PositiveFeedbackLeftCount" propertyName:@"positiveFeedbackLeftCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"positiveFeedbackLeftCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NegativeFeedbackLeftCount" propertyName:@"negativeFeedbackLeftCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"negativeFeedbackLeftCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NeutralFeedbackLeftCount" propertyName:@"neutralFeedbackLeftCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"neutralFeedbackLeftCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FeedbackLeftPercent" propertyName:@"feedbackLeftPercent" type:PICO_TYPE_FLOAT clazz:nil];
    [map setObject:ps forKey:@"feedbackLeftPercent"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RepeatBuyerCount" propertyName:@"repeatBuyerCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"repeatBuyerCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RepeatBuyerPercent" propertyName:@"repeatBuyerPercent" type:PICO_TYPE_FLOAT clazz:nil];
    [map setObject:ps forKey:@"repeatBuyerPercent"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UniqueBuyerCount" propertyName:@"uniqueBuyerCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"uniqueBuyerCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TransactionPercent" propertyName:@"transactionPercent" type:PICO_TYPE_FLOAT clazz:nil];
    [map setObject:ps forKey:@"transactionPercent"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CrossBorderTransactionCount" propertyName:@"crossBorderTransactionCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"crossBorderTransactionCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CrossBorderTransactionPercent" propertyName:@"crossBorderTransactionPercent" type:PICO_TYPE_FLOAT clazz:nil];
    [map setObject:ps forKey:@"crossBorderTransactionPercent"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.positiveFeedbackLeftCount = nil;
    self.negativeFeedbackLeftCount = nil;
    self.neutralFeedbackLeftCount = nil;
    self.feedbackLeftPercent = nil;
    self.repeatBuyerCount = nil;
    self.repeatBuyerPercent = nil;
    self.uniqueBuyerCount = nil;
    self.transactionPercent = nil;
    self.crossBorderTransactionCount = nil;
    self.crossBorderTransactionPercent = nil;
    self.any = nil;
    [super dealloc];
}

@end
