// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_ValidateTestUserRegistrationRequestType.h"

@implementation Trading_ValidateTestUserRegistrationRequestType

@synthesize feedbackScore = _feedbackScore;
@synthesize registrationDate = _registrationDate;
@synthesize subscribeSA = _subscribeSA;
@synthesize subscribeSAPro = _subscribeSAPro;
@synthesize subscribeSM = _subscribeSM;
@synthesize subscribeSMPro = _subscribeSMPro;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ValidateTestUserRegistrationRequest" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FeedbackScore" propertyName:@"feedbackScore" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"feedbackScore"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RegistrationDate" propertyName:@"registrationDate" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"registrationDate"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubscribeSA" propertyName:@"subscribeSA" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"subscribeSA"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubscribeSAPro" propertyName:@"subscribeSAPro" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"subscribeSAPro"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubscribeSM" propertyName:@"subscribeSM" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"subscribeSM"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubscribeSMPro" propertyName:@"subscribeSMPro" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"subscribeSMPro"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.feedbackScore = nil;
    self.registrationDate = nil;
    self.subscribeSA = nil;
    self.subscribeSAPro = nil;
    self.subscribeSM = nil;
    self.subscribeSMPro = nil;
    [super dealloc];
}

@end
