// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 This type is deprecated as <b>GetProduct*</b> calls were deprecated.
 
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 
 High end of the range.
 
*/
extern NSString *const Trading_RangeCodeType_HIGH;

/**
 
 
 Low end of the range.
 
*/
extern NSString *const Trading_RangeCodeType_LOW;

/**
 
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_RangeCodeType_CUSTOM_CODE;
