// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_AddMemberMessagesAAQToBidderResponseContainerType.h"

@implementation Trading_AddMemberMessagesAAQToBidderResponseContainerType

@synthesize correlationID = _correlationID;
@synthesize ack = _ack;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CorrelationID" propertyName:@"correlationID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"correlationID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Ack" propertyName:@"ack" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"ack"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.correlationID = nil;
    self.ack = nil;
    [super dealloc];
}

@end
