// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 This type is deprecated as the <b>GetProduct*</b> calls are no longer available.
 
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_CharacteristicSetIDsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_id;

}


/**
 
 
 Numeric identifier for a domain (characteristic set).<br>
 <br>
 For GetProductSearchResults (for selling tools), it's best to use
 GetCategory2CS to determine mappings between categories and
 characteristic sets that are flagged as CatalogEnabled.
 
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *id;


@end
