// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_PaymentOptionsGroupEnabledCodeType.h"

/**
 @file
 
 Enumerated type that lists the possible states for DE and AT categories in regards to the new eBay payment process. 
 
*/

/**
 
 This value indicates that the new eBay payment process is enabled for this category.
 
*/
NSString *const Trading_PaymentOptionsGroupEnabledCodeType_E_BAY_PAYMENT_PROCESS_ENABLED = @"eBayPaymentProcessEnabled";

/**
 
 This value indicates that non-standard payments is enabled for this category. 
 
*/
NSString *const Trading_PaymentOptionsGroupEnabledCodeType_NON_STANDARD_PAYMENTS_ENABLED = @"NonStandardPaymentsEnabled";

/**
 
 This value indicates that the new eBay payment process is excluded for this category.
 
*/
NSString *const Trading_PaymentOptionsGroupEnabledCodeType_E_BAY_PAYMENT_PROCESS_EXCLUDED = @"eBayPaymentProcessExcluded";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_PaymentOptionsGroupEnabledCodeType_CUSTOM_CODE = @"CustomCode";
