// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 This type is deprecated as Pictures Manager was retired.
 
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 
 (in) All pictures, folders, and account settings. Default value.
 
*/
extern NSString *const Trading_PictureManagerDetailLevelCodeType_RETURN_ALL;

/**
 
 
 (in) Only data about the account subscription.
 
*/
extern NSString *const Trading_PictureManagerDetailLevelCodeType_RETURN_SUBSCRIPTION;

/**
 
 
 (in) Return only data about pictures and folders in the authenticated user's account.
 
*/
extern NSString *const Trading_PictureManagerDetailLevelCodeType_RETURN_PICTURE;

/**
 
 
 (out) Reserved for internal or future use
 
*/
extern NSString *const Trading_PictureManagerDetailLevelCodeType_CUSTOM_CODE;
