// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_RefundArrayType.h"
#import "Trading_RefundType.h"

@implementation Trading_RefundArrayType

@synthesize refund = _refund;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Refund" propertyName:@"refund" type:PICO_TYPE_OBJECT clazz:[Trading_RefundType class]];
    [map setObject:ps forKey:@"refund"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.refund = nil;
    [super dealloc];
}

@end
