// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_UnitOfMeasurementType.h"

@implementation Trading_UnitOfMeasurementType

@synthesize alternateText = _alternateText;
@synthesize suggestedText = _suggestedText;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"AlternateText" propertyName:@"alternateText" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"alternateText"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SuggestedText" propertyName:@"suggestedText" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"suggestedText"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.alternateText = nil;
    self.suggestedText = nil;
    self.any = nil;
    [super dealloc];
}

@end
