// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_SellingSummaryType.h"
#import "Trading_AmountType.h"

@implementation Trading_SellingSummaryType

@synthesize activeAuctionCount = _activeAuctionCount;
@synthesize auctionSellingCount = _auctionSellingCount;
@synthesize auctionBidCount = _auctionBidCount;
@synthesize totalAuctionSellingValue = _totalAuctionSellingValue;
@synthesize totalSoldCount = _totalSoldCount;
@synthesize totalSoldValue = _totalSoldValue;
@synthesize soldDurationInDays = _soldDurationInDays;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ActiveAuctionCount" propertyName:@"activeAuctionCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"activeAuctionCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AuctionSellingCount" propertyName:@"auctionSellingCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"auctionSellingCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AuctionBidCount" propertyName:@"auctionBidCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"auctionBidCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalAuctionSellingValue" propertyName:@"totalAuctionSellingValue" type:PICO_TYPE_OBJECT clazz:[Trading_AmountType class]];
    [map setObject:ps forKey:@"totalAuctionSellingValue"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalSoldCount" propertyName:@"totalSoldCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"totalSoldCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalSoldValue" propertyName:@"totalSoldValue" type:PICO_TYPE_OBJECT clazz:[Trading_AmountType class]];
    [map setObject:ps forKey:@"totalSoldValue"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SoldDurationInDays" propertyName:@"soldDurationInDays" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"soldDurationInDays"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.activeAuctionCount = nil;
    self.auctionSellingCount = nil;
    self.auctionBidCount = nil;
    self.totalAuctionSellingValue = nil;
    self.totalSoldCount = nil;
    self.totalSoldValue = nil;
    self.soldDurationInDays = nil;
    [super dealloc];
}

@end
