// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_StoreLogoType;

/**
 
 Set of Store logos.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_StoreLogoArrayType : NSObject <PicoBindable> {

@private
    NSMutableArray *_logo;

}


/**
 
 A Store logo.
 
 
 entry type : class Trading_StoreLogoType
*/

@property (nonatomic, retain) NSMutableArray *logo;


@end
