// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup EBayAPIInterface
*/
@interface Trading_WarrantyOfferedDetailsType : NSObject <PicoBindable> {

@private
    NSString *_warrantyOfferedOption;
    NSString *_description;
    NSMutableArray *_any;

}


/**
 
 Whether the item includes a warranty.
 This value can be passed in the AddItem family of calls.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *warrantyOfferedOption;

/**
 
 Display string that applications can use to present the "warranty offered" options in
 a more user-friendly format (such as in a drop-down list).
 Not applicable as input to the AddItem family of calls. (Use WarrantyOfferedOption instead.)
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *description;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
