// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_OfferType.h"
#import "Trading_UserType.h"
#import "Trading_AmountType.h"

@implementation Trading_OfferType

@synthesize action = _action;
@synthesize currency = _currency;
@synthesize itemID = _itemID;
@synthesize maxBid = _maxBid;
@synthesize quantity = _quantity;
@synthesize secondChanceEnabled = _secondChanceEnabled;
@synthesize siteCurrency = _siteCurrency;
@synthesize timeBid = _timeBid;
@synthesize highestBid = _highestBid;
@synthesize convertedPrice = _convertedPrice;
@synthesize transactionID = _transactionID;
@synthesize user = _user;
@synthesize userConsent = _userConsent;
@synthesize bidCount = _bidCount;
@synthesize message = _message;
@synthesize bestOfferID = _bestOfferID;
@synthesize myMaxBid = _myMaxBid;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Action" propertyName:@"action" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"action"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Currency" propertyName:@"currency" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"currency"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemID" propertyName:@"itemID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaxBid" propertyName:@"maxBid" type:PICO_TYPE_OBJECT clazz:[Trading_AmountType class]];
    [map setObject:ps forKey:@"maxBid"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Quantity" propertyName:@"quantity" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"quantity"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SecondChanceEnabled" propertyName:@"secondChanceEnabled" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"secondChanceEnabled"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SiteCurrency" propertyName:@"siteCurrency" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"siteCurrency"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TimeBid" propertyName:@"timeBid" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"timeBid"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"HighestBid" propertyName:@"highestBid" type:PICO_TYPE_OBJECT clazz:[Trading_AmountType class]];
    [map setObject:ps forKey:@"highestBid"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ConvertedPrice" propertyName:@"convertedPrice" type:PICO_TYPE_OBJECT clazz:[Trading_AmountType class]];
    [map setObject:ps forKey:@"convertedPrice"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TransactionID" propertyName:@"transactionID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"transactionID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"User" propertyName:@"user" type:PICO_TYPE_OBJECT clazz:[Trading_UserType class]];
    [map setObject:ps forKey:@"user"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserConsent" propertyName:@"userConsent" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"userConsent"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BidCount" propertyName:@"bidCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"bidCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Message" propertyName:@"message" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"message"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BestOfferID" propertyName:@"bestOfferID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"bestOfferID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MyMaxBid" propertyName:@"myMaxBid" type:PICO_TYPE_OBJECT clazz:[Trading_AmountType class]];
    [map setObject:ps forKey:@"myMaxBid"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.action = nil;
    self.currency = nil;
    self.itemID = nil;
    self.maxBid = nil;
    self.quantity = nil;
    self.secondChanceEnabled = nil;
    self.siteCurrency = nil;
    self.timeBid = nil;
    self.highestBid = nil;
    self.convertedPrice = nil;
    self.transactionID = nil;
    self.user = nil;
    self.userConsent = nil;
    self.bidCount = nil;
    self.message = nil;
    self.bestOfferID = nil;
    self.myMaxBid = nil;
    self.any = nil;
    [super dealloc];
}

@end
