// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 Shows the pagination of data returned by call requests.
 Pagination of returned data is not needed nor
 supported for every Trading API call. See the documentation for
 individual calls to determine whether pagination is
 supported, required, or desirable.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_PaginationResultType : NSObject <PicoBindable> {

@private
    NSNumber *_totalNumberOfPages;
    NSNumber *_totalNumberOfEntries;
    NSMutableArray *_any;

}


/**
 
 Indicates the total number of pages of data that could be returned by repeated
 requests. Returned with a value of 0 if no pages are available.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalNumberOfPages;

/**
 
 Indicates the total number of entries that could be returned by repeated
 call requests. Returned with a value of 0 if no entries are available.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalNumberOfEntries;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
