// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_SellerDashboardAlertType;

/**
 
 Type defining the <b>PowerSellerStatus</b> container returned in the 
 <b>GetSellerDashboard</b> response. The <b>PowerSellerStatus</b> 
 container is only returned if the seller making the call is a Power Seller.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_PowerSellerDashboardType : NSObject <PicoBindable> {

@private
    NSString *_level;
    NSMutableArray *_alert;
    NSMutableArray *_any;

}


/**
 
 This field indicates the seller's eBay PowerSeller tier. PowerSellers are
 distinguished in five tiers based on average monthly sales. Benefits and services vary
 for each tier. eBay calculates eligibility for each tier on a monthly basis.
 
 
 type: string constant in Trading_SellerLevelCodeType.h
*/
@property (nonatomic, retain) NSString *level;

/**
 
 The <b>PowerSellerStatus.Alert</b> container is only returned if eBay
 has posted one or more informational or warning messages related to the seller's 
 PowerSeller status.
 
 
 entry type : class Trading_SellerDashboardAlertType
*/

@property (nonatomic, retain) NSMutableArray *alert;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
