// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractResponseType.h"



/**
 
 Response for deleting a Selling Manager template.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_DeleteSellingManagerTemplateResponseType : Trading_AbstractResponseType {

@private
    NSString *_deletedSaleTemplateID;
    NSString *_deletedSaleTemplateName;

}


/**
 
 The unique identifier of the template.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *deletedSaleTemplateID;

/**
 
 The name of the Selling Manager template.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *deletedSaleTemplateName;


@end
