// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_CategoryType;

/**
 
 Container for a list of categories.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_CategoryArrayType : NSObject <PicoBindable> {

@private
    NSMutableArray *_category;

}


/**
 
 Contains details about one category. For GetCategories,
 this node is not returned when no detail level is specified.
 
 
 entry type : class Trading_CategoryType
*/

@property (nonatomic, retain) NSMutableArray *category;


@end
