// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_GetVeROReportStatusRequestType.h"
#import "Trading_PaginationType.h"

@implementation Trading_GetVeROReportStatusRequestType

@synthesize veROReportPacketID = _veROReportPacketID;
@synthesize itemID = _itemID;
@synthesize includeReportedItemDetails = _includeReportedItemDetails;
@synthesize timeFrom = _timeFrom;
@synthesize timeTo = _timeTo;
@synthesize pagination = _pagination;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetVeROReportStatusRequest" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"VeROReportPacketID" propertyName:@"veROReportPacketID" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"veROReportPacketID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemID" propertyName:@"itemID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IncludeReportedItemDetails" propertyName:@"includeReportedItemDetails" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"includeReportedItemDetails"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TimeFrom" propertyName:@"timeFrom" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"timeFrom"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TimeTo" propertyName:@"timeTo" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"timeTo"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Pagination" propertyName:@"pagination" type:PICO_TYPE_OBJECT clazz:[Trading_PaginationType class]];
    [map setObject:ps forKey:@"pagination"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.veROReportPacketID = nil;
    self.itemID = nil;
    self.includeReportedItemDetails = nil;
    self.timeFrom = nil;
    self.timeTo = nil;
    self.pagination = nil;
    [super dealloc];
}

@end
