// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Indicates a specific type of lead generation format listing (within the classified and localmarketbestofferonly subtypes, which include the general ClassifiedAd and LocalMarketBestOfferOnly subtype).
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 General classified ad listing subtype.
                <br/><br/>
                <span class="tablenote">
                <strong>Note:</strong> This value indicates a classified ad (or digital download) listing on <strong>ebay.com</strong> websites, not on <strong>ebayclassifieds.com</strong>. The ebayclassifieds.com site is not supported by the Trading API. For information about other differences between these two sites, see <a href="http://pages.ebay.com/help/sell/classified.html">Advertising with classified ads on eBay and eBay Classifieds</a>.
                </span>
 
*/
extern NSString *const Trading_ListingSubtypeCodeType_CLASSIFIED_AD;

/**
 
 General LocalMarketBestOfferOnly listing subtype.
 
*/
extern NSString *const Trading_ListingSubtypeCodeType_LOCAL_MARKET_BEST_OFFER_ONLY;

/**
 
 Reserved for internal or future use
 
*/
extern NSString *const Trading_ListingSubtypeCodeType_CUSTOM_CODE;
