// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_PromotionRuleType;

/**
 
 This type is deprecated as Cross Promotions are no longer supported in the APIs.
 
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_PromotionRuleArrayType : NSObject <PicoBindable> {

@private
    NSMutableArray *_promotionRule;

}


/**
 
 
 A container consisting of details related to an eBay Store promotion rule. One or 
 more <b>PromotionRule</b> containers may be returned in 
 <b>GetPromotionRules</b>.
 
 
 entry type : class Trading_PromotionRuleType
*/

@property (nonatomic, retain) NSMutableArray *promotionRule;


@end
