// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_CalculatedShippingRateOptionCodeType.h"

/**
 @file
 
 Calculated Shipping Rate Options.
 
*/

/**
 
 Calculate the Actual Shipping Rate from Combined Item Weight
 
*/
NSString *const Trading_CalculatedShippingRateOptionCodeType_COMBINED_ITEM_WEIGHT = @"CombinedItemWeight";

/**
 
 Calculate the Actual Shipping Rate from Individual Item Weight
 
*/
NSString *const Trading_CalculatedShippingRateOptionCodeType_INDIVIDUAL_ITEM_WEIGHT = @"IndividualItemWeight";

/**
 
 Reserved for internal or future use.
 
*/
NSString *const Trading_CalculatedShippingRateOptionCodeType_CUSTOM_CODE = @"CustomCode";
