// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_StoreColorSchemeArrayType.h"
#import "Trading_StoreColorSchemeType.h"

@implementation Trading_StoreColorSchemeArrayType

@synthesize colorScheme = _colorScheme;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ColorScheme" propertyName:@"colorScheme" type:PICO_TYPE_OBJECT clazz:[Trading_StoreColorSchemeType class]];
    [map setObject:ps forKey:@"colorScheme"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.colorScheme = nil;
    [super dealloc];
}

@end
