// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_UnitOfMeasurementType;

/**
 
 Type defining the <b>UnitOfMeasurementDetails</b> container, which consists 
 of suggested and alternative ways of referring to units of measurement.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_UnitOfMeasurementDetailsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_unitOfMeasurement;
    NSString *_detailVersion;
    NSDate *_updateTime;
    NSMutableArray *_any;

}


/**
 
 Container consisting of suggested (<b>SuggestedText</b> values) and
 alternative ways (<b>AlternateText</b> values) of referring to units of
 measurement.
 
 
 entry type : class Trading_UnitOfMeasurementType
*/

@property (nonatomic, retain) NSMutableArray *unitOfMeasurement;

/**
 
 Returns the latest version number for this field. The version can be
 used to determine if and when to refresh cached client data.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *detailVersion;

/**
 
 Gives the time in GMT that the feature flags for the details were last
 updated. This timestamp can be used to determine if and when to refresh
 cached client data.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *updateTime;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
