// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_GetMyeBaySellingResponseType.h"
#import "Trading_PaginatedItemArrayType.h"
#import "Trading_SellingSummaryType.h"
#import "Trading_PaginatedOrderTransactionArrayType.h"
#import "Trading_MyeBaySellingSummaryType.h"

@implementation Trading_GetMyeBaySellingResponseType

@synthesize sellingSummary = _sellingSummary;
@synthesize scheduledList = _scheduledList;
@synthesize activeList = _activeList;
@synthesize soldList = _soldList;
@synthesize unsoldList = _unsoldList;
@synthesize summary = _summary;
@synthesize bidList = _bidList;
@synthesize deletedFromSoldList = _deletedFromSoldList;
@synthesize deletedFromUnsoldList = _deletedFromUnsoldList;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetMyeBaySellingResponse" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SellingSummary" propertyName:@"sellingSummary" type:PICO_TYPE_OBJECT clazz:[Trading_SellingSummaryType class]];
    [map setObject:ps forKey:@"sellingSummary"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ScheduledList" propertyName:@"scheduledList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedItemArrayType class]];
    [map setObject:ps forKey:@"scheduledList"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ActiveList" propertyName:@"activeList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedItemArrayType class]];
    [map setObject:ps forKey:@"activeList"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SoldList" propertyName:@"soldList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedOrderTransactionArrayType class]];
    [map setObject:ps forKey:@"soldList"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UnsoldList" propertyName:@"unsoldList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedItemArrayType class]];
    [map setObject:ps forKey:@"unsoldList"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Summary" propertyName:@"summary" type:PICO_TYPE_OBJECT clazz:[Trading_MyeBaySellingSummaryType class]];
    [map setObject:ps forKey:@"summary"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BidList" propertyName:@"bidList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedItemArrayType class]];
    [map setObject:ps forKey:@"bidList"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DeletedFromSoldList" propertyName:@"deletedFromSoldList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedOrderTransactionArrayType class]];
    [map setObject:ps forKey:@"deletedFromSoldList"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DeletedFromUnsoldList" propertyName:@"deletedFromUnsoldList" type:PICO_TYPE_OBJECT clazz:[Trading_PaginatedItemArrayType class]];
    [map setObject:ps forKey:@"deletedFromUnsoldList"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.sellingSummary = nil;
    self.scheduledList = nil;
    self.activeList = nil;
    self.soldList = nil;
    self.unsoldList = nil;
    self.summary = nil;
    self.bidList = nil;
    self.deletedFromSoldList = nil;
    self.deletedFromUnsoldList = nil;
    [super dealloc];
}

@end
