// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 Retrieves the tax table for a user on a given site or retrieves the valid
 jurisdictions (if any) for a given site.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_GetTaxTableRequestType : Trading_AbstractRequestType {

@private

}



@end
