// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_PictureFormatCodeType.h"

/**
 @file
 
 JPG or GIF format.
 
*/

/**
 
 JPG format.
 
*/
NSString *const Trading_PictureFormatCodeType_JPG = @"JPG";

/**
 
 GIF format.
 
*/
NSString *const Trading_PictureFormatCodeType_GIF = @"GIF";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_PictureFormatCodeType_CUSTOM_CODE = @"CustomCode";
