// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_AddTransactionConfirmationItemResponseType.h"

@implementation Trading_AddTransactionConfirmationItemResponseType

@synthesize itemID = _itemID;
@synthesize startTime = _startTime;
@synthesize endTime = _endTime;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"AddTransactionConfirmationItemResponse" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemID" propertyName:@"itemID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"StartTime" propertyName:@"startTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"startTime"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EndTime" propertyName:@"endTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"endTime"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.itemID = nil;
    self.startTime = nil;
    self.endTime = nil;
    [super dealloc];
}

@end
