// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 List of possible statuses for Store custom pages.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 The page is visible.
 
*/
extern NSString *const Trading_StoreCustomPageStatusCodeType_ACTIVE;

/**
 
 The page is to be deleted.
 
*/
extern NSString *const Trading_StoreCustomPageStatusCodeType_DELETE;

/**
 
 The page is not visible.
 
*/
extern NSString *const Trading_StoreCustomPageStatusCodeType_INACTIVE;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreCustomPageStatusCodeType_CUSTOM_CODE;
