// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 RecommendationEngineCodeType - Type declaration to be used by other schema.
 Identifies the engines that can be used to analyze proposed listing data.
 See the Developer's Guide for a list of recommendation engines that
 are currently operational.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 (in) Listing Analyzer engine; Returns tips related to fields
 that a seller wants to specify in a listing.
 
*/
extern NSString *const Trading_RecommendationEngineCodeType_LISTING_ANALYZER;

/**
 
 (in) Reserved for internal or future use.
 
*/
extern NSString *const Trading_RecommendationEngineCodeType_SIFFTAS;

/**
 
 (in) Product Pricing engine. Returns average start and sold prices
 of completed items that were listed a specified product ID.
 
*/
extern NSString *const Trading_RecommendationEngineCodeType_PRODUCT_PRICING;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_RecommendationEngineCodeType_CUSTOM_CODE;

/**
 
 (in) Suggested Attributes engine. Returns suggested attributes
 and catalog products (for Pre-filled Item Information) that have been
 used by other sellers who listed similar items in the same category.
 
*/
extern NSString *const Trading_RecommendationEngineCodeType_SUGGESTED_ATTRIBUTES;

/**
 
 (in) Custom Item Specifics engine. Returns the most popular
 names and values to use for custom Item Specifics based the
 requested category (and the Title, if specified).
 
*/
extern NSString *const Trading_RecommendationEngineCodeType_ITEM_SPECIFICS;
