// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_FeedbackTypeCodeType.h"

/**
 @file
 
 These are the codes used to specify the type of feedback/feedbacktype in a single feedback record. Additional information about feedback is available in the
 online Help of the eBay website.
 
*/

/**
 
 Retrieves feedback left by all buyers for this user.
 
*/
NSString *const Trading_FeedbackTypeCodeType_FEEDBACK_RECEIVED_AS_SELLER = @"FeedbackReceivedAsSeller";

/**
 
 Retrieves feedback left by all sellers for this user.
 
*/
NSString *const Trading_FeedbackTypeCodeType_FEEDBACK_RECEIVED_AS_BUYER = @"FeedbackReceivedAsBuyer";

/**
 
 Retrieves feedback left by all buyers and all sellers for this user.
 
*/
NSString *const Trading_FeedbackTypeCodeType_FEEDBACK_RECEIVED = @"FeedbackReceived";

/**
 
 Feedback left for others.
 
*/
NSString *const Trading_FeedbackTypeCodeType_FEEDBACK_LEFT = @"FeedbackLeft";

/**
 
 Reserved for internal or future use.
 
*/
NSString *const Trading_FeedbackTypeCodeType_CUSTOM_CODE = @"CustomCode";
