// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_ProductRecommendationsType.h"
#import "Trading_ProductInfoType.h"

@implementation Trading_ProductRecommendationsType

@synthesize product = _product;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Product" propertyName:@"product" type:PICO_TYPE_OBJECT clazz:[Trading_ProductInfoType class]];
    [map setObject:ps forKey:@"product"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.product = nil;
    [super dealloc];
}

@end
