// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_DisputeMessageType.h"

@implementation Trading_DisputeMessageType

@synthesize messageID = _messageID;
@synthesize messageSource = _messageSource;
@synthesize messageCreationTime = _messageCreationTime;
@synthesize messageText = _messageText;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageID" propertyName:@"messageID" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"messageID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageSource" propertyName:@"messageSource" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"messageSource"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageCreationTime" propertyName:@"messageCreationTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"messageCreationTime"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageText" propertyName:@"messageText" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"messageText"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.messageID = nil;
    self.messageSource = nil;
    self.messageCreationTime = nil;
    self.messageText = nil;
    self.any = nil;
    [super dealloc];
}

@end
