// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_DiscountCodeType.h"

/**
 @file
 
 Specifies which discount type to use.
 
*/

/**
 
 Specifies discount type as percentage.
 
*/
NSString *const Trading_DiscountCodeType_PERCENTAGE = @"Percentage";

/**
 
 Specifies discount type as a fixed amount. Discount will be in the 
 currency of the original listing.
 
*/
NSString *const Trading_DiscountCodeType_PRICE = @"Price";

/**
 
 Future use
 
*/
NSString *const Trading_DiscountCodeType_CUSTOM_CODE = @"CustomCode";
