// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


/**
 
 A number with a possible decimal point, e.g. -3.14159.
 (Item Specifics don't distinguish between float and double.)
 
*/
extern NSString *const Trading_ValueTypeCodeType_DECIMAL;

/**
 
 Free-form text. This is the default. 
 Max length 50.
 
*/
extern NSString *const Trading_ValueTypeCodeType_TEXT;

/**
 
 International Standard Book Number (ISBN).
 ISBNs can contain either 10 or 13 characters.
 Max length 13.
 
*/
extern NSString *const Trading_ValueTypeCodeType_ISBN;

/**
 
 Universal Product Code. Max length 12.
 
*/
extern NSString *const Trading_ValueTypeCodeType_UPC;

/**
 
 European Article Number. Max length 13.
 
*/
extern NSString *const Trading_ValueTypeCodeType_EAN;

/**
 
 A Date value, which can assume one of these formats:
 YYYYMMDD, YYYYMM, or YYYY. See ValueFormat for the 
 recommended format to use in listings.
 
*/
extern NSString *const Trading_ValueTypeCodeType_DATE;

/**
 
 Reserved for future use.
 
*/
extern NSString *const Trading_ValueTypeCodeType_CUSTOM_CODE;
