// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 These are payment methods that sellers can use to pay eBay fees.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Used for all other payment methods which are not specifically listed in other columns.
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_NOTHING_ON_FILE;

/**
 
 Credit Card
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_CREDIT_CARD;

/**
 
 PayPal
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_PAY_PAL;

/**
 
 Direct Debit
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_DIRECT_DEBIT;

/**
 
  Direct Debit, pending signature mandate
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_DIRECT_DEBIT_PENDING_SIGNATURE_MANDATE;

/**
 
  eBay Direct Pay
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_E_BAY_DIRECT_PAY;

/**
 
 (out) Reserved for internal or future use
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_CUSTOM_CODE;

/**
 
  Direct Debit, pending verification
 
*/
extern NSString *const Trading_SellerPaymentMethodCodeType_DIRECT_DEBIT_PENDING_VERIFICATION;
