// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Indicates the source of the item's eligibility for the Buyer
 Protection Program.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Buyer protection is covered by the PayPal Protection Program.
 
*/
extern NSString *const Trading_AuthTokenTypeCodeType_CLIENT_ALERTS_TOKEN;

/**
 
  Reserved for internal or future use.
 
*/
extern NSString *const Trading_AuthTokenTypeCodeType_CUSTOM_CODE;
