// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Specifies how cross-promoted items with gallery images
 should be displayed.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Show any items, in no particular order.
 
*/
extern NSString *const Trading_GallerySortFilterCodeType_SHOW_ANY_ITEMS;

/**
 
 Show items with gallery images first, before
 other items.
 
*/
extern NSString *const Trading_GallerySortFilterCodeType_SHOW_ITEMS_WITH_GALLERY_IMAGES_FIRST;

/**
 
 Show only items with gallery images.
 
*/
extern NSString *const Trading_GallerySortFilterCodeType_SHOW_ONLY_ITEMS_WITH_GALLERY_IMAGES;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_GallerySortFilterCodeType_CUSTOM_CODE;
