// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_BidAssistantListType.h"

@implementation Trading_BidAssistantListType

@synthesize bidGroupID = _bidGroupID;
@synthesize includeNotes = _includeNotes;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BidGroupID" propertyName:@"bidGroupID" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"bidGroupID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IncludeNotes" propertyName:@"includeNotes" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"includeNotes"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.bidGroupID = nil;
    self.includeNotes = nil;
    self.any = nil;
    [super dealloc];
}

@end
