// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_SellingManagerAutoSecondChanceOfferTypeCodeType.h"

/**
 @file
 
 SellingManagerAutoSecondChanceOfferTypeCodeType - Specifies the type of second chance offer automation rule that will be added to an item.
 
*/

/**
 
 Sends a second chance offer to all bidders who bid more than a specific amount.
 
*/
NSString *const Trading_SellingManagerAutoSecondChanceOfferTypeCodeType_BIDS_GREATER_THAN_AMOUNT = @"BidsGreaterThanAmount";

/**
 
 Sends a second chance offer to all bidders who bid more than the cost plus a specific amount.
 
*/
NSString *const Trading_SellingManagerAutoSecondChanceOfferTypeCodeType_BIDS_GREATER_THAN_COST_PLUS_AMOUNT = @"BidsGreaterThanCostPlusAmount";

/**
 
 Sends a second chance offer to all bidders who bid more than the cost plus a specific percentage.
 
*/
NSString *const Trading_SellingManagerAutoSecondChanceOfferTypeCodeType_BIDS_GREATER_THAN_COST_PLUS_PERCENTAGE = @"BidsGreaterThanCostPlusPercentage";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_SellingManagerAutoSecondChanceOfferTypeCodeType_CUSTOM_CODE = @"CustomCode";
