// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_MyMessagesAlertArrayType.h"
#import "Trading_MyMessagesAlertType.h"

@implementation Trading_MyMessagesAlertArrayType

@synthesize alert = _alert;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Alert" propertyName:@"alert" type:PICO_TYPE_OBJECT clazz:[Trading_MyMessagesAlertType class]];
    [map setObject:ps forKey:@"alert"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.alert = nil;
    [super dealloc];
}

@end
