// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 ProStores listing level preferences.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_ListingCheckoutRedirectPreferenceType : NSObject <PicoBindable> {

@private
    NSString *_proStoresStoreName;
    NSString *_sellerThirdPartyUsername;
    NSMutableArray *_any;

}


/**
 
 The name of the ProStores store.
 To remove this value when revising or relisting an item, use DeletedField.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *proStoresStoreName;

/**
 
 The user name of the ProStores store.
 To remove this value when revising or relisting an item, use DeletedField.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sellerThirdPartyUsername;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
