// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 Defines properties associated with a particular event.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_NotificationEventPropertyType : NSObject <PicoBindable> {

@private
    NSString *_eventType;
    NSString *_name;
    NSString *_value;
    NSMutableArray *_any;

}


/**
 
 The name of the notification event.
 
 
 type: string constant in Trading_NotificationEventTypeCodeType.h
*/
@property (nonatomic, retain) NSString *eventType;

/**
 
 Specify property name associated with an particular event.
 
 
 type: string constant in Trading_NotificationEventPropertyNameCodeType.h
*/
@property (nonatomic, retain) NSString *name;

/**
 
 Specifies the value for the property.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *value;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
