// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 This type is deprecated as Pictures Manager was retired.
 
 Manager account.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 
 (in) Adds a folder or setting  to the account.
 
*/
extern NSString *const Trading_PictureManagerActionCodeType_ADD;

/**
 
 
 (in) Deletes a folder or setting from the account.
 
*/
extern NSString *const Trading_PictureManagerActionCodeType_DELETE;

/**
 
 
 (in) Renames a folder or picture.
 
*/
extern NSString *const Trading_PictureManagerActionCodeType_RENAME;

/**
 
 
 (in) Moves a picture to the user's default folder in the 
 default album. If the picture is already there, 
 then no action occurs.
 
*/
extern NSString *const Trading_PictureManagerActionCodeType_MOVE;

/**
 
 
 (in) Changes a subscription level.
 
*/
extern NSString *const Trading_PictureManagerActionCodeType_CHANGE;

/**
 
 
 (out) Reserved for internal or future use
 
*/
extern NSString *const Trading_PictureManagerActionCodeType_CUSTOM_CODE;
