// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_SellingManagerAlertTypeCodeType.h"

/**
 @file
 
 Container for various alert types.
 
*/

/**
 
 Indicates that an alert related to a sold listing has been issued.
 
*/
NSString *const Trading_SellingManagerAlertTypeCodeType_SOLD = @"Sold";

/**
 
 Indicates that an alert related to inventory has been issued.
 
*/
NSString *const Trading_SellingManagerAlertTypeCodeType_INVENTORY = @"Inventory";

/**
 
 Indicates that an automation alert has been sent because a listing did
 not conform to listing automation rules.
 
*/
NSString *const Trading_SellingManagerAlertTypeCodeType_AUTOMATION = @"Automation";

/**
 
 Indicates that an alert related to PaisaPay, a payment method used for eBay
 India, has been issued.
 
*/
NSString *const Trading_SellingManagerAlertTypeCodeType_PAISA_PAY = @"PaisaPay";

/**
 
 Indicates that an alert has been issued for negative feedback received, bad
 email, or an unpaid item dispute.
 
*/
NSString *const Trading_SellingManagerAlertTypeCodeType_GENERAL = @"General";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_SellingManagerAlertTypeCodeType_CUSTOM_CODE = @"CustomCode";
