// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 The purpose of a purchase (e.g., by a PayPal application).
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Custom Code
 
*/
extern NSString *const Trading_PurchasePurposeTypeCodeType_OTHER;

extern NSString *const Trading_PurchasePurposeTypeCodeType_BUY_NOW_ITEM;

extern NSString *const Trading_PurchasePurposeTypeCodeType_SHOPPING_CART;

extern NSString *const Trading_PurchasePurposeTypeCodeType_AUCTION_ITEM;

extern NSString *const Trading_PurchasePurposeTypeCodeType_GIFT_CERTIFICATES;

extern NSString *const Trading_PurchasePurposeTypeCodeType_SUBSCRIPTION;

extern NSString *const Trading_PurchasePurposeTypeCodeType_DONATION;

extern NSString *const Trading_PurchasePurposeTypeCodeType_E_BAY_BILLING;

/**
 
 (out) Reserved for internal or future use
 
*/
extern NSString *const Trading_PurchasePurposeTypeCodeType_CUSTOM_CODE;
