// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Valid notification status codes
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Status indicating the notification is newly created
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_NEW;

/**
 
 Status indicating the notification was failed
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_FAILED;

/**
 
 Status indicating the end user application is marked down
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_MARKED_DOWN;

/**
 
 Status indicating the notification is pending
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_PENDING;

/**
 
 Status indicating the notification is failed pending
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_FAILED_PENDING;

/**
 
 Status indicating the notification is marked down pending
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_MARKED_DOWN_PENDING;

/**
 
 Status indicating the notification was successfully delivered
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_DELIVERED;

/**
 
 Status indicating the notification was unable to deliver
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_UNDELIVERABLE;

/**
 
 Status indicating the notification was rejected
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_REJECTED;

/**
 
 Status indicating the notification was cancelled
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_CANCELED;

/**
 
 Reserved for future internal or external use
 
*/
extern NSString *const Trading_NotificationEventStateCodeType_CUSTOM_CODE;
