// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 These are the various summary periods for which feedback is calculated.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Period including the last 30 days from today.
 
*/
extern NSString *const Trading_FeedbackSummaryPeriodCodeType_THIRTY_DAYS;

/**
 
 Period including the last 52 weeks from today.
 
*/
extern NSString *const Trading_FeedbackSummaryPeriodCodeType_FIFTY_TWO_WEEKS;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_FeedbackSummaryPeriodCodeType_CUSTOM_CODE;
