// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_SellingManagerAutoListType.h"
#import "Trading_SellingManagerAutoListAccordingToScheduleType.h"
#import "Trading_SellingManagerAutoListMinActiveItemsType.h"

@implementation Trading_SellingManagerAutoListType

@synthesize sourceSaleTemplateID = _sourceSaleTemplateID;
@synthesize keepMinActive = _keepMinActive;
@synthesize listAccordingToSchedule = _listAccordingToSchedule;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SourceSaleTemplateID" propertyName:@"sourceSaleTemplateID" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"sourceSaleTemplateID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"KeepMinActive" propertyName:@"keepMinActive" type:PICO_TYPE_OBJECT clazz:[Trading_SellingManagerAutoListMinActiveItemsType class]];
    [map setObject:ps forKey:@"keepMinActive"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ListAccordingToSchedule" propertyName:@"listAccordingToSchedule" type:PICO_TYPE_OBJECT clazz:[Trading_SellingManagerAutoListAccordingToScheduleType class]];
    [map setObject:ps forKey:@"listAccordingToSchedule"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.sourceSaleTemplateID = nil;
    self.keepMinActive = nil;
    self.listAccordingToSchedule = nil;
    self.any = nil;
    [super dealloc];
}

@end
