// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Values to be used in choosing that an uploaded picture is added to the available pictures on the eBay site.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Specifies that an uploaded picture is added to the pictures available to a
 seller on the eBay site.
 
*/
extern NSString *const Trading_PictureUploadPolicyCodeType_ADD;

/**
 
 Specifies, first, that all pictures available to a seller on the eBay site are
 removed, and then second, that the currently uploaded picture is made
 available to the seller.
  
*/
extern NSString *const Trading_PictureUploadPolicyCodeType_CLEAR_AND_ADD;

/**
 
  (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_PictureUploadPolicyCodeType_CUSTOM_CODE;
