// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_CheckoutMethodCodeType.h"

/**
 @file
 
  This type is deprecated as the 3rd Party Checkout is no longer available.
 
 
*/

/**
 
 
 Other Checkout Method was used.
 
*/
NSString *const Trading_CheckoutMethodCodeType_OTHER = @"Other";

/**
 
 
 As of July 1, 2011, third-party applications can no longer be used for
 checkout. All purchased items must go through the eBay Checkout flow.
 
*/
NSString *const Trading_CheckoutMethodCodeType_THIRD_PARTY_CHECKOUT = @"ThirdPartyCheckout";

/**
 
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_CheckoutMethodCodeType_CUSTOM_CODE = @"CustomCode";
