// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_SellerShippingProfileType.h"

@implementation Trading_SellerShippingProfileType

@synthesize shippingProfileID = _shippingProfileID;
@synthesize shippingProfileName = _shippingProfileName;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingProfileID" propertyName:@"shippingProfileID" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"shippingProfileID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingProfileName" propertyName:@"shippingProfileName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"shippingProfileName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.shippingProfileID = nil;
    self.shippingProfileName = nil;
    self.any = nil;
    [super dealloc];
}

@end
