// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 Container of token and image URL and Audio URL.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_BotBlockResponseType : NSObject <PicoBindable> {

@private
    NSString *_botBlockToken;
    NSString *_botBlockUrl;
    NSString *_botBlockAudioUrl;
    NSMutableArray *_any;

}


/**
 
 An encrypted token generated by eBay when the botblock
 mechanism is triggered. This token is mapped to BotBlockUrl 
 and BotBlockAudioUrl.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *botBlockToken;

/**
 
 The URL of the image that your application should display to
 the user for a botblock challenge.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *botBlockUrl;

/**
 
 The URL of the audio-clip that your application should provide for sight-impaired users.
 The BotBlockAudioUrl audio-clip corresponds to the BotBlockUrl image.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *botBlockAudioUrl;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
