// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Seller account status.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 Your account is current.
 
*/
extern NSString *const Trading_SellerAccountStatusCodeType_CURRENT;

/**
 
 Your account is past due. 
 
*/
extern NSString *const Trading_SellerAccountStatusCodeType_PAST_DUE;

/**
 
 Your account is on hold and risking suspension. 
 
*/
extern NSString *const Trading_SellerAccountStatusCodeType_ON_HOLD;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_SellerAccountStatusCodeType_CUSTOM_CODE;
