// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_ConditionEnabledCodeType.h"

/**
 @file
 
 Values indicate whether the ConditionID field is enabled, disabled or required for a category.
 
*/

/**
 
 Item condition is not supported for the category. 
 Do not pass ConditionID in AddItem and related calls.
 
*/
NSString *const Trading_ConditionEnabledCodeType_DISABLED = @"Disabled";

/**
 
 Item condition is supported for the category. 
 You can pass ConditionID to specify the condition 
 in AddItem and related calls.
 
*/
NSString *const Trading_ConditionEnabledCodeType_ENABLED = @"Enabled";

/**
 
 Item condition is required for the category. 
 You must use ConditionID to specify the condition 
 in AddItem and related calls.
 
*/
NSString *const Trading_ConditionEnabledCodeType_REQUIRED = @"Required";

/**
 
 (out) Reserved for internal or future use.
   
*/
NSString *const Trading_ConditionEnabledCodeType_CUSTOM_CODE = @"CustomCode";
