// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 Enumerated type that defines the eBay user's account type.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
 This value indicates that the eBay user's account is a Partially Provisioned Account
 without buying and selling privileges on eBay.
 
*/
extern NSString *const Trading_BusinessRoleType_SHOPPER;

/**
 
 This value indicates that the eBay user's account is a fully provisioned account with buying
 and selling privileges on eBay.
 
*/
extern NSString *const Trading_BusinessRoleType_FULL_MARKET_PLACE_PARTICIPANT;
