// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_ReviseSellingManagerTemplateRequestType.h"
#import "Trading_ItemType.h"

@implementation Trading_ReviseSellingManagerTemplateRequestType

@synthesize saleTemplateID = _saleTemplateID;
@synthesize productID = _productID;
@synthesize saleTemplateName = _saleTemplateName;
@synthesize item = _item;
@synthesize deletedField = _deletedField;
@synthesize verifyOnly = _verifyOnly;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ReviseSellingManagerTemplateRequest" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SaleTemplateID" propertyName:@"saleTemplateID" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"saleTemplateID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProductID" propertyName:@"productID" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"productID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SaleTemplateName" propertyName:@"saleTemplateName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"saleTemplateName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Item" propertyName:@"item" type:PICO_TYPE_OBJECT clazz:[Trading_ItemType class]];
    [map setObject:ps forKey:@"item"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"DeletedField" propertyName:@"deletedField" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"deletedField"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"VerifyOnly" propertyName:@"verifyOnly" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"verifyOnly"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.saleTemplateID = nil;
    self.productID = nil;
    self.saleTemplateName = nil;
    self.item = nil;
    self.deletedField = nil;
    self.verifyOnly = nil;
    [super dealloc];
}

@end
