// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 Returns a seller's Ask Seller a Question (ASQ) subjects, each in
 its own Subject node.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_GetMessagePreferencesRequestType : Trading_AbstractRequestType {

@private
    NSString *_sellerID;
    NSNumber *_includeASQPreferences;

}


/**
 
 The ID of the user to retrieve ASQ subjects for. This
 value must be specified in the request, but does not
 need to be the same user as the user making the
 request.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sellerID;

/**
 
 If true, indicates that the ASQ subjects for the
 specified user should be returned.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *includeASQPreferences;


@end
