// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


/**
 
 Do not return warnings when the application passes
 unrecognized or deprecated elements in a request.
 This is the default value if WarningLevel is not specified.
  
*/
extern NSString *const Trading_WarningLevelCodeType_LOW;

/**
 
 Return warnings when the application passes
 unrecognized or deprecated elements in a request.
 
*/
extern NSString *const Trading_WarningLevelCodeType_HIGH;
