// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_RemoveFromWatchListRequestType.h"
#import "Trading_VariationKeyType.h"

@implementation Trading_RemoveFromWatchListRequestType

@synthesize itemID = _itemID;
@synthesize removeAllItems = _removeAllItems;
@synthesize variationKey = _variationKey;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"RemoveFromWatchListRequest" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ItemID" propertyName:@"itemID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemID"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RemoveAllItems" propertyName:@"removeAllItems" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"removeAllItems"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"VariationKey" propertyName:@"variationKey" type:PICO_TYPE_OBJECT clazz:[Trading_VariationKeyType class]];
    [map setObject:ps forKey:@"variationKey"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.itemID = nil;
    self.removeAllItems = nil;
    self.variationKey = nil;
    [super dealloc];
}

@end
