// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 User's eBay Store subscription level.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
    (in) This closes your eBay Store and cancels your eBay Store subscription.
    All of your current Store Inventory items (if any) will end automatically.
    All of your current Online Auction and Fixed Price items will remain active
    until their ending date is reached or they are sold. All your Store pictures
    hosted on eBay will be deleted unless you have a Picture Manager
    subscription.
 
*/
extern NSString *const Trading_StoreSubscriptionLevelCodeType_CLOSE;

/**
 
    Basic level subscription.
 
*/
extern NSString *const Trading_StoreSubscriptionLevelCodeType_BASIC;

/**
 
    Featured level subscription.
 
*/
extern NSString *const Trading_StoreSubscriptionLevelCodeType_FEATURED;

/**
 
    Anchor level subscription.
 
*/
extern NSString *const Trading_StoreSubscriptionLevelCodeType_ANCHOR;

/**
 
    (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreSubscriptionLevelCodeType_CUSTOM_CODE;
