// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_SellingManagerShippedStatusCodeType.h"

/**
 @file
 
 Contains values for shipped status.
 
*/

/**
 
 The shipped status is "shipped."
 
*/
NSString *const Trading_SellingManagerShippedStatusCodeType_SHIPPED = @"Shipped";

/**
 
 The shipped status is "unshipped."
 
*/
NSString *const Trading_SellingManagerShippedStatusCodeType_UNSHIPPED = @"Unshipped";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Trading_SellingManagerShippedStatusCodeType_CUSTOM_CODE = @"CustomCode";
