// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_XMLRequesterCredentialsType : NSObject <PicoBindable> {

@private
    NSString *_username;
    NSString *_password;
    NSString *_eBayAuthToken;
    NSMutableArray *_any;

}


/**
 
 eBay user ID (i.e., eBay.com Web site login name) for the user the application
 is retrieving a token for. This is typically the application's end-user (not
 the developer).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *username;

/**
 
 Password for the user specified in Username.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *password;

/**
 
 Authentication token representing the user who is making the request. The
 user's token must be retrieved from eBay. To determine a user's authentication
 token, see the Authentication and Authorization information in the eBay Web
 Services guide. For calls that list or retrieve item or transaction data, the
 user usually needs to be the seller of the item in question or, in some cases,
 the buyer. Similarly, calls that retrieve user or account data may be
 restricted to the user whose data is being requested. The documentation for
 each call includes information about such restrictions.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *eBayAuthToken;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
