// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
     CharityStatusCodeType - Type declaration to be used by other schema.
     Indicates the nonprofit status of the nonprofit charity organization registered with the dedicated eBay Giving Works provider.
 
 
 @ingroup EBayAPIInterface
*/

/**
 
   (out)The specified nonprofit charity organization is a valid nonprofit charity organization according to the requirements of the dedicated eBay Giving Works provider.
 
*/
extern NSString *const Trading_CharityStatusCodeType_VALID;

/**
 
   (out)The specified nonprofit charity organization is no longer a valid nonprofit charity organization according to the requirements of the dedicated eBay Giving Works provider.
 
*/
extern NSString *const Trading_CharityStatusCodeType_NO_LONGER_VALID;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_CharityStatusCodeType_CUSTOM_CODE;
