// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractResponseType.h"



/**
 
 Includes the authentication token for the user and the date it expires.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_FetchTokenResponseType : Trading_AbstractResponseType {

@private
    NSString *_eBayAuthToken;
    NSDate *_hardExpirationTime;
    NSString *_restToken;

}


/**
 
 The authentication token for the user.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *eBayAuthToken;

/**
 
 Date and time at which the token returned in eBayAuthToken expires
 and can no longer be used to authenticate the user for that application.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *hardExpirationTime;

/**
 
 The REST authentication token for the user.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *restToken;


@end
