// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Trading_NameValueRelationshipType.h"

@implementation Trading_NameValueRelationshipType

@synthesize parentName = _parentName;
@synthesize parentValue = _parentValue;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ParentName" propertyName:@"parentName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"parentName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ParentValue" propertyName:@"parentValue" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"parentValue"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.parentName = nil;
    self.parentValue = nil;
    self.any = nil;
    [super dealloc];
}

@end
