// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_NotificationPayloadTypeCodeType.h"

/**
 @file
 
 The schema options for Platform Notifications.
 
*/

/**
 
 New Schema format (used by the new schema XML API and SOAP API).
 
*/
NSString *const Trading_NotificationPayloadTypeCodeType_E_BL_SCHEMA_SOAP = @"eBLSchemaSOAP";

/**
 
 Reserved for internal or future use
 
*/
NSString *const Trading_NotificationPayloadTypeCodeType_CUSTOM_CODE = @"CustomCode";
