// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Trading_StoreVacationPreferencesType;

/**
 
 Store Preferences type.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_StorePreferencesType : NSObject <PicoBindable> {

@private
    Trading_StoreVacationPreferencesType *_vacationPreferences;

}


/**
 
 Store vacation hold preferences.
 
 
 type : class Trading_StoreVacationPreferencesType
*/
@property (nonatomic, retain) Trading_StoreVacationPreferencesType *vacationPreferences;


@end
