// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 <b>No longer recommended.</b> The eBay Store Cross Promotions are no longer
 supported in the Trading API. Retrieves a list of upsell or cross-sell items associated
 with the specified Item ID.
 
 
 @ingroup EBayAPIInterface
*/
@interface Trading_GetCrossPromotionsRequestType : Trading_AbstractRequestType {

@private
    NSString *_itemID;
    NSString *_promotionMethod;
    NSString *_promotionViewMode;

}


/**
 
 The unique ID of the referring item. The cross-promoted
 items will supplement this item.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 The cross-promotion method you want to use for the
 returned list, either UpSell or CrossSell.
 
 
 type: string constant in Trading_PromotionMethodCodeType.h
*/
@property (nonatomic, retain) NSString *promotionMethod;

/**
 
 The role of the person requesting to view the cross-promoted
 items, either seller or buyer. Default is buyer.
 
 
 type: string constant in Trading_TradingRoleCodeType.h
*/
@property (nonatomic, retain) NSString *promotionViewMode;


@end
