// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Trading_ApplicationDeviceTypeCodeType.h"

/**
 @file
 
 Device used.
 
*/

/**
 
 Browser device.
 
*/
NSString *const Trading_ApplicationDeviceTypeCodeType_BROWSER = @"Browser";

/**
 
 Wireless device.
 
*/
NSString *const Trading_ApplicationDeviceTypeCodeType_WIRELESS = @"Wireless";

/**
 
 Desktop device.
 
*/
NSString *const Trading_ApplicationDeviceTypeCodeType_DESKTOP = @"Desktop";

/**
 
 SetTopTVBox device.
 
*/
NSString *const Trading_ApplicationDeviceTypeCodeType_SET_TOP_TV_BOX = @"SetTopTVBox";

/**
 
 Reserved for future use.
 
*/
NSString *const Trading_ApplicationDeviceTypeCodeType_CUSTOM_CODE = @"CustomCode";
