// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Shopping_SellerBusinessCodeType.h"

/**
 @file
 
 Type of seller account. This value can be returned if the German site (site ID
 77) or eBay Motors site (site ID 100) is specified.
 
*/

/**
 
 Type of seller account not defined.
 
*/
NSString *const Shopping_SellerBusinessCodeType_UNDEFINED = @"Undefined";

/**
 
 Private seller account.
 
*/
NSString *const Shopping_SellerBusinessCodeType_PRIVATE = @"Private";

/**
 
 Commercial seller account.
 
*/
NSString *const Shopping_SellerBusinessCodeType_COMMERCIAL = @"Commercial";

/**
 
 (out) Reserved for internal or future use.
 
*/
NSString *const Shopping_SellerBusinessCodeType_CUSTOM_CODE = @"CustomCode";
