// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Shopping_AbstractRequestType.h"



/**
 
 Gets the official eBay system time in GMT.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_GeteBayTimeRequestType : Shopping_AbstractRequestType {

@private

}



@end
