// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Shopping_NameValueListArrayType.h"
#import "Shopping_NameValueListType.h"

@implementation Shopping_NameValueListArrayType

@synthesize nameValueList = _nameValueList;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"NameValueList" propertyName:@"nameValueList" type:PICO_TYPE_OBJECT clazz:[Shopping_NameValueListType class]];
    [map setObject:ps forKey:@"nameValueList"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.nameValueList = nil;
    [super dealloc];
}

@end
