// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 Product ID has an attribute of ProductIDCodeType and a string value.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_ProductIDType : NSObject <PicoBindable> {

@private
    NSString *_value;
    NSString *_type;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *value;

/**
 (public property)
 
 type: string constant in Shopping_ProductIDCodeType.h
*/
@property (nonatomic, retain) NSString *type;


@end
