// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import "BarCodeSoap_SOAPClient.h"

@implementation BarCodeSoap_SOAPClient

-(void)generateBarCode:(GenerateBarCode *) requestObject 
      success:(void (^)(GenerateBarCodeResponse *responseObject))success
      failure:(void (^)(NSError *error, id<PicoBindable> soapFault))failure {
 
     [super setDefaultHeader:@"SOAPAction" value: @"http://www.webservicex.net/GenerateBarCode"];
 
     [super invoke:requestObject responseClass:[GenerateBarCodeResponse class]
     success:^(PicoSOAPRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoSOAPRequestOperation *operation, NSError *error, id<PicoBindable> soapFault) {
         if (failure) {
             failure(error, soapFault);
         }
     }];
}


@end