// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "BaseServiceResponse.h"


@class ExtensionType;
@class CategoryHistogramContainer;
@class ConditionHistogramContainer;
@class AspectHistogramContainer;

/**
 
 Response container for the getHistogram call.
 
 
 @ingroup FindingServicePortType
*/
@interface GetHistogramsResponse : BaseServiceResponse {

@private
    CategoryHistogramContainer *_categoryHistogramContainer;
    AspectHistogramContainer *_aspectHistogramContainer;
    ConditionHistogramContainer *_conditionHistogramContainer;
    NSMutableArray *_extension;

}


/**
 
 Response container for category histograms. This container is
 returned only when the specified category has children categories.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 Category histograms may not be available for some parent categories
 on the eBay Motors site.
 </span>
 
 
 type : class CategoryHistogramContainer
*/
@property (nonatomic, retain) CategoryHistogramContainer *categoryHistogramContainer;

/**
 
 Response container for aspect histograms. Aspect histograms are
 returned for categories that have been mapped to domains only. In
 most cases, just leaf categories are mapped to domains, but there are
 exceptions.
 
 
 type : class AspectHistogramContainer
*/
@property (nonatomic, retain) AspectHistogramContainer *aspectHistogramContainer;

/**
 
 Response container for condition histograms.
 Returned for leaf and parent categories.<br>
 <br>
 Only returned when you search the eBay US site (as of
 February 2011). International items in US search results
 are included in the histogram counts.
 
 
 type : class ConditionHistogramContainer
*/
@property (nonatomic, retain) ConditionHistogramContainer *conditionHistogramContainer;

/**
 
 Reserved for future use.
 
 
 entry type : class ExtensionType
*/

@property (nonatomic, retain) NSMutableArray *extension;


@end
