// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "ArrayOfForecast.h"
#import "Forecast.h"

@implementation ArrayOfForecast

@synthesize forecast = _forecast;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Forecast" propertyName:@"forecast" type:PICO_TYPE_OBJECT clazz:[Forecast class]];
    [map setObject:ps forKey:@"forecast"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.forecast = nil;
    [super dealloc];
}

@end
