// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class ItemMetaData;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface CartCreateItem : NSObject <PicoBindable> {

@private
    NSString *_asin;
    NSString *_offerListingId;
    NSNumber *_quantity;
    NSString *_associateTag;
    NSString *_listItemId;
    NSMutableArray *_metaData;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *asin;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *offerListingId;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *quantity;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *associateTag;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *listItemId;

/**
 (public property)
 
 entry type : class ItemMetaData
*/

@property (nonatomic, retain) NSMutableArray *metaData;


@end
