// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Shopping_HalfCatalogProductType;

/**
 
 Information about an eBay catalog product.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_HalfProductsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_product;
    NSMutableArray *_any;

}


/**
 
 A set of Half.com catalog products. This contains stock information about a
 particular DVD, book, or other product.
 When you use QueryKeywords in the request, FindHalfProducts returns a
 maximum of 20 products per page.
 When you use ProductID in the request, FindHalfProducts usually only
 returns 1 product. ItemCount is only returned when ProductID is used
 in the request and the IncludeSelector is set to Items or Details.
 (If more than one product matches the same ProductID,
 FindProducts will return all of those products. As of the time
 of this writing, we expect this to be a rare case.)
 
 
 entry type : class Shopping_HalfCatalogProductType
*/

@property (nonatomic, retain) NSMutableArray *product;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
