// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Finding_SellingStatus.h"
#import "Finding_Amount.h"

@implementation Finding_SellingStatus

@synthesize currentPrice = _currentPrice;
@synthesize convertedCurrentPrice = _convertedCurrentPrice;
@synthesize bidCount = _bidCount;
@synthesize sellingState = _sellingState;
@synthesize timeLeft = _timeLeft;
@synthesize delimiter = _delimiter;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"currentPrice" propertyName:@"currentPrice" type:PICO_TYPE_OBJECT clazz:[Finding_Amount class]];
    [map setObject:ps forKey:@"currentPrice"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"convertedCurrentPrice" propertyName:@"convertedCurrentPrice" type:PICO_TYPE_OBJECT clazz:[Finding_Amount class]];
    [map setObject:ps forKey:@"convertedCurrentPrice"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"bidCount" propertyName:@"bidCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"bidCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"sellingState" propertyName:@"sellingState" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"sellingState"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"timeLeft" propertyName:@"timeLeft" type:PICO_TYPE_DURATION clazz:nil];
    [map setObject:ps forKey:@"timeLeft"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"delimiter" propertyName:@"delimiter" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"delimiter"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.currentPrice = nil;
    self.convertedCurrentPrice = nil;
    self.bidCount = nil;
    self.sellingState = nil;
    self.timeLeft = nil;
    self.delimiter = nil;
    self.any = nil;
    [super dealloc];
}

@end
