// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Finding_BestMatchFindingServiceRequest.h"
#import "Finding_Affiliate.h"
#import "Finding_PaginationInput.h"

@implementation Finding_BestMatchFindingServiceRequest

@synthesize paginationInput = _paginationInput;
@synthesize buyerPostalCode = _buyerPostalCode;
@synthesize affiliate = _affiliate;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"paginationInput" propertyName:@"paginationInput" type:PICO_TYPE_OBJECT clazz:[Finding_PaginationInput class]];
    [map setObject:ps forKey:@"paginationInput"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"buyerPostalCode" propertyName:@"buyerPostalCode" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"buyerPostalCode"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"affiliate" propertyName:@"affiliate" type:PICO_TYPE_OBJECT clazz:[Finding_Affiliate class]];
    [map setObject:ps forKey:@"affiliate"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.paginationInput = nil;
    self.buyerPostalCode = nil;
    self.affiliate = nil;
    [super dealloc];
}

@end
