// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Finding_GetSearchKeywordsRecommendationResponse.h"
#import "Finding_ExtensionType.h"

@implementation Finding_GetSearchKeywordsRecommendationResponse

@synthesize keywords = _keywords;
@synthesize extension = _extension;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"getSearchKeywordsRecommendationResponse" nsUri:@"http://www.ebay.com/marketplace/search/v1/services"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"keywords" propertyName:@"keywords" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"keywords"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"extension" propertyName:@"extension" type:PICO_TYPE_OBJECT clazz:[Finding_ExtensionType class]];
    [map setObject:ps forKey:@"extension"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.keywords = nil;
    self.extension = nil;
    [super dealloc];
}

@end
