// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "BrowseNodeLookupRequest.h"

@implementation BrowseNodeLookupRequest

@synthesize browseNodeId = _browseNodeId;
@synthesize responseGroup = _responseGroup;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"BrowseNodeId" propertyName:@"browseNodeId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"browseNodeId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ResponseGroup" propertyName:@"responseGroup" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"responseGroup"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.browseNodeId = nil;
    self.responseGroup = nil;
    [super dealloc];
}

@end
