// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class EditorialReview;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface EditorialReviews : NSObject <PicoBindable> {

@private
    NSMutableArray *_editorialReview;

}


/**
 (public property)
 
 entry type : class EditorialReview
*/

@property (nonatomic, retain) NSMutableArray *editorialReview;


@end
