// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "ItemLookupRequest.h"

@implementation ItemLookupRequest

@synthesize condition = _condition;
@synthesize idType = _idType;
@synthesize merchantId = _merchantId;
@synthesize itemId = _itemId;
@synthesize responseGroup = _responseGroup;
@synthesize searchIndex = _searchIndex;
@synthesize variationPage = _variationPage;
@synthesize relatedItemPage = _relatedItemPage;
@synthesize relationshipType = _relationshipType;
@synthesize includeReviewsSummary = _includeReviewsSummary;
@synthesize truncateReviewsAt = _truncateReviewsAt;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Condition" propertyName:@"condition" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"condition"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IdType" propertyName:@"idType" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"idType"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MerchantId" propertyName:@"merchantId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"merchantId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ItemId" propertyName:@"itemId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ResponseGroup" propertyName:@"responseGroup" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"responseGroup"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SearchIndex" propertyName:@"searchIndex" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"searchIndex"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"VariationPage" propertyName:@"variationPage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"variationPage"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RelatedItemPage" propertyName:@"relatedItemPage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"relatedItemPage"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"RelationshipType" propertyName:@"relationshipType" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"relationshipType"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IncludeReviewsSummary" propertyName:@"includeReviewsSummary" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"includeReviewsSummary"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TruncateReviewsAt" propertyName:@"truncateReviewsAt" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"truncateReviewsAt"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.condition = nil;
    self.idType = nil;
    self.merchantId = nil;
    self.itemId = nil;
    self.responseGroup = nil;
    self.searchIndex = nil;
    self.variationPage = nil;
    self.relatedItemPage = nil;
    self.relationshipType = nil;
    self.includeReviewsSummary = nil;
    self.truncateReviewsAt = nil;
    [super dealloc];
}

@end
