// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Player;

/**
 (public class)
 
*/
@interface Party : NSObject <PicoBindable> {

@private
    NSMutableArray *_player;

}


/**
 (public property)
 
 entry type : class Player
*/

@property (nonatomic, retain) NSMutableArray *player;


@end
