// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Accessories.h"
#import "Accessory.h"

@implementation Accessories

@synthesize accessory = _accessory;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"Accessories" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Accessory" propertyName:@"accessory" type:PICO_TYPE_OBJECT clazz:[Accessory class]];
    [map setObject:ps forKey:@"accessory"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.accessory = nil;
    [super dealloc];
}

@end
