// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Cart;
@class OperationRequest;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface CartAddResponse : NSObject <PicoBindable> {

@private
    OperationRequest *_operationRequest;
    NSMutableArray *_cart;

}


/**
 (public property)
 
 type : class OperationRequest
*/
@property (nonatomic, retain) OperationRequest *operationRequest;

/**
 (public property)
 
 entry type : class Cart
*/

@property (nonatomic, retain) NSMutableArray *cart;


@end
