// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "Offers.h"
#import "Offer.h"

@implementation Offers

@synthesize totalOffers = _totalOffers;
@synthesize totalOfferPages = _totalOfferPages;
@synthesize moreOffersUrl = _moreOffersUrl;
@synthesize offer = _offer;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"Offers" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalOffers" propertyName:@"totalOffers" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"totalOffers"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalOfferPages" propertyName:@"totalOfferPages" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"totalOfferPages"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MoreOffersUrl" propertyName:@"moreOffersUrl" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"moreOffersUrl"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Offer" propertyName:@"offer" type:PICO_TYPE_OBJECT clazz:[Offer class]];
    [map setObject:ps forKey:@"offer"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.totalOffers = nil;
    self.totalOfferPages = nil;
    self.moreOffersUrl = nil;
    self.offer = nil;
    [super dealloc];
}

@end
