// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Disc;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface Tracks : NSObject <PicoBindable> {

@private
    NSMutableArray *_disc;

}


/**
 (public property)
 
 entry type : class Disc
*/

@property (nonatomic, retain) NSMutableArray *disc;


@end
